export const builderThemes = [
  {
    id: "tech-blue",
    name: "Tech Blue",
    category: "Professional",
    light: {
      primary: "#0F172A",
      accent: "#3B82F6",
      background: "#E5F0FF",
      text: "#1E293B",
      font: "Inter",
    },
    dark: {
      primary: "#1E293B",
      accent: "#2563EB",
      background: "#0F172A",
      text: "#E5F7FF",
      font: "Inter",
    },
  },
  {
    id: "luxury-gold",
    name: "Luxury Gold",
    category: "Premium",
    light: {
      primary: "#000000",
      accent: "#FFD700",
      background: "#F5F5F5",
      text: "#1A1A1A",
      font: "Playfair Display",
    },
    dark: {
      primary: "#1A1A1A",
      accent: "#E6C200",
      background: "#000000",
      text: "#F5F5F5",
      font: "Playfair Display",
    },
  },
  {
    id: "pastel-peach",
    name: "Pastel Peach",
    category: "Beauty",
    light: {
      primary: "#FDE5EC",
      accent: "#F8B195",
      background: "#FFF9F9",
      text: "#333333",
      font: "Poppins",
    },
    dark: {
      primary: "#333333",
      accent: "#F28E79",
      background: "#FDE5EC",
      text: "#FFF9F9",
      font: "Poppins",
    },
  },
  {
    id: "modern-mint",
    name: "Modern Mint",
    category: "Health",
    light: {
      primary: "#10B981",
      accent: "#06B6D4",
      background: "#ECFDF5",
      text: "#065F46",
      font: "Inter",
    },
    dark: {
      primary: "#065F46",
      accent: "#0E7490",
      background: "#0F172A",
      text: "#ECFDF5",
      font: "Inter",
    },
  },
  {
    id: "corporate-gray",
    name: "Corporate Gray",
    category: "Business",
    light: {
      primary: "#4B5563",
      accent: "#2563EB",
      background: "#F3F4F6",
      text: "#111827",
      font: "Roboto",
    },
    dark: {
      primary: "#1F2937",
      accent: "#1D4ED8",
      background: "#111827",
      text: "#F3F4F6",
      font: "Roboto",
    },
  },
  {
    id: "health-green",
    name: "Health Green",
    category: "Health",
    light: {
      primary: "#047857",
      accent: "#10B981",
      background: "#ECFDF5",
      text: "#064E3B",
      font: "Lato",
    },
    dark: {
      primary: "#064E3B",
      accent: "#047857",
      background: "#1F2937",
      text: "#ECFDF5",
      font: "Lato",
    },
  },
  {
    id: "fintech-purple",
    name: "Fintech Purple",
    category: "Finance",
    light: {
      primary: "#6D28D9",
      accent: "#A78BFA",
      background: "#F5F3FF",
      text: "#2D026B",
      font: "Open Sans",
    },
    dark: {
      primary: "#2D026B",
      accent: "#7C3AED",
      background: "#1F1A2E",
      text: "#EDE9FE",
      font: "Open Sans",
    },
  },
  {
    id: "minimal-black-white",
    name: "Minimal Black White",
    category: "Minimal",
    light: {
      primary: "#FFFFFF",
      accent: "#000000",
      background: "#F9FAFB",
      text: "#111827",
      font: "Helvetica Neue",
    },
    dark: {
      primary: "#111827",
      accent: "#F9FAFB",
      background: "#000000",
      text: "#FFFFFF",
      font: "Helvetica Neue",
    },
  },
  {
    id: "retro-coral",
    name: "Retro Coral",
    category: "Creative",
    light: {
      primary: "#FF6B6B",
      accent: "#FFE66D",
      background: "#FFF5E1",
      text: "#333333",
      font: "Merriweather",
    },
    dark: {
      primary: "#333333",
      accent: "#FFD964",
      background: "#353535",
      text: "#FFF5E1",
      font: "Merriweather",
    },
  },
  {
    id: "ocean-deep",
    name: "Ocean Deep",
    category: "Professional",
    light: {
      primary: "#0EA5E9",
      accent: "#0284C7",
      background: "#EFF6FF",
      text: "#1E3A8A",
      font: "Nunito",
    },
    dark: {
      primary: "#1E3A8A",
      accent: "#0369A1",
      background: "#0F172A",
      text: "#EFF6FF",
      font: "Nunito",
    },
  },
  {
    id: "elegant-plum",
    name: "Elegant Plum",
    category: "Premium",
    light: {
      primary: "#8B5CF6",
      accent: "#C084FC",
      background: "#F8F5FF",
      text: "#3F3C7E",
      font: "Cormorant Garamond",
    },
    dark: {
      primary: "#3F3C7E",
      accent: "#A855F7",
      background: "#1F1C3B",
      text: "#F8F5FF",
      font: "Cormorant Garamond",
    },
  },
  {
    id: "sunny-yellow",
    name: "Sunny Yellow",
    category: "Creative",
    light: {
      primary: "#FBBF24",
      accent: "#F59E0B",
      background: "#FFFBEB",
      text: "#92400E",
      font: "Rubik",
    },
    dark: {
      primary: "#92400E",
      accent: "#D97706",
      background: "#1F1D15",
      text: "#FFFBEB",
      font: "Rubik",
    },
  },
  {
    id: "forest-moss",
    name: "Forest Moss",
    category: "Nature",
    light: {
      primary: "#4D7C0F",
      accent: "#86EFAC",
      background: "#F0FDF4",
      text: "#1F2937",
      font: "PT Sans",
    },
    dark: {
      primary: "#1F2937",
      accent: "#4D7C0F",
      background: "#11200F",
      text: "#F0FDF4",
      font: "PT Sans",
    },
  },
  {
    id: "vintage-rose",
    name: "Vintage Rose",
    category: "Beauty",
    light: {
      primary: "#BE185D",
      accent: "#F472B6",
      background: "#FFF1F2",
      text: "#701A36",
      font: "Libre Baskerville",
    },
    dark: {
      primary: "#701A36",
      accent: "#DB2777",
      background: "#1E0D18",
      text: "#FFF1F2",
      font: "Libre Baskerville",
    },
  },
  {
    id: "urban-slate",
    name: "Urban Slate",
    category: "Modern",
    light: {
      primary: "#374151",
      accent: "#6B7280",
      background: "#F9FAFB",
      text: "#111827",
      font: "Lato",
    },
    dark: {
      primary: "#111827",
      accent: "#4B5563",
      background: "#1F2937",
      text: "#F9FAFB",
      font: "Lato",
    },
  },
  {
    id: "soft-lavender",
    name: "Soft Lavender",
    category: "Beauty",
    light: {
      primary: "#C4B5FD",
      accent: "#A78BFA",
      background: "#F9F5FF",
      text: "#4C1D95",
      font: "Raleway",
    },
    dark: {
      primary: "#4C1D95",
      accent: "#764BA2",
      background: "#2E103A",
      text: "#F9F5FF",
      font: "Raleway",
    },
  },
  {
    id: "autumn-orange",
    name: "Autumn Orange",
    category: "Creative",
    light: {
      primary: "#EA580C",
      accent: "#F97316",
      background: "#FFF7ED",
      text: "#7C2D12",
      font: "Oxygen",
    },
    dark: {
      primary: "#7C2D12",
      accent: "#EA580C",
      background: "#2B0E02",
      text: "#FFF7ED",
      font: "Oxygen",
    },
  },
  {
    id: "aqua-marine",
    name: "Aqua Marine",
    category: "Health",
    light: {
      primary: "#14B8A6",
      accent: "#2DD4BF",
      background: "#ECFEF9",
      text: "#0F766E",
      font: "Source Sans Pro",
    },
    dark: {
      primary: "#0F766E",
      accent: "#14B8A6",
      background: "#1E3A37",
      text: "#ECFEF9",
      font: "Source Sans Pro",
    },
  },
  {
    id: "peach-coral",
    name: "Peach Coral",
    category: "Beauty",
    light: {
      primary: "#FFDDD2",
      accent: "#FF9F71",
      background: "#FFF7F3",
      text: "#4A312C",
      font: "Nunito",
    },
    dark: {
      primary: "#4A312C",
      accent: "#FF9F71",
      background: "#2C1A19",
      text: "#FFF7F3",
      font: "Nunito",
    },
  },
  {
    id: "slate-ocean",
    name: "Slate Ocean",
    category: "Professional",
    light: {
      primary: "#334155",
      accent: "#64748B",
      background: "#F1F5F9",
      text: "#0F172A",
      font: "Work Sans",
    },
    dark: {
      primary: "#0F172A",
      accent: "#334155",
      background: "#1E293B",
      text: "#F1F5F9",
      font: "Work Sans",
    },
  },
  {
    id: "rosewood",
    name: "Rosewood",
    category: "Premium",
    light: {
      primary: "#881337",
      accent: "#BE185D",
      background: "#FDF2F8",
      text: "#3B021F",
      font: "Crimson Pro",
    },
    dark: {
      primary: "#3B021F",
      accent: "#881337",
      background: "#2E0B17",
      text: "#FDF2F8",
      font: "Crimson Pro",
    },
  },
];

export const themeCategories = [
  { id: "all", name: "All Themes" },
  { id: "Professional", name: "Professional" },
  { id: "Premium", name: "Premium" },
  { id: "Beauty", name: "Beauty & Wellness" },
  { id: "Health", name: "Health & Medical" },
  { id: "Business", name: "Business" },
  { id: "Finance", name: "Finance & Tech" },
  { id: "Creative", name: "Creative & Arts" },
  { id: "Minimal", name: "Minimal" },
  { id: "Nature", name: "Nature & Eco" },
  { id: "Modern", name: "Modern" },
];

export function getThemesByCategory(category) {
  if (category === "all") return builderThemes;
  return builderThemes.filter((theme) => theme.category === category);
}

export function getThemeById(id) {
  return builderThemes.find((theme) => theme.id === id);
}
